// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: kakaoTalk.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_TEXT   MessageType = 0
	MessageType_SYSTEM MessageType = 1
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TEXT",
		1: "SYSTEM",
	}
	MessageType_value = map[string]int32{
		"TEXT":   0,
		"SYSTEM": 1,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_kakaoTalk_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_kakaoTalk_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_kakaoTalk_proto_rawDescGZIP(), []int{0}
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=chat.MessageType" json:"type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_kakaoTalk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kakaoTalk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_kakaoTalk_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type MessageHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHistoryRequest) Reset() {
	*x = MessageHistoryRequest{}
	mi := &file_kakaoTalk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHistoryRequest) ProtoMessage() {}

func (x *MessageHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kakaoTalk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHistoryRequest.ProtoReflect.Descriptor instead.
func (*MessageHistoryRequest) Descriptor() ([]byte, []int) {
	return file_kakaoTalk_proto_rawDescGZIP(), []int{1}
}

func (x *MessageHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MessageHistoryRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type BulkMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSent     int32                  `protobuf:"varint,1,opt,name=total_sent,json=totalSent,proto3" json:"total_sent,omitempty"`
	Successful    int32                  `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkMessageResponse) Reset() {
	*x = BulkMessageResponse{}
	mi := &file_kakaoTalk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkMessageResponse) ProtoMessage() {}

func (x *BulkMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kakaoTalk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkMessageResponse.ProtoReflect.Descriptor instead.
func (*BulkMessageResponse) Descriptor() ([]byte, []int) {
	return file_kakaoTalk_proto_rawDescGZIP(), []int{2}
}

func (x *BulkMessageResponse) GetTotalSent() int32 {
	if x != nil {
		return x.TotalSent
	}
	return 0
}

func (x *BulkMessageResponse) GetSuccessful() int32 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *BulkMessageResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *BulkMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kakaoTalk_proto protoreflect.FileDescriptor

const file_kakaoTalk_proto_rawDesc = "" +
	"\n" +
	"\x0fkakaoTalk.proto\x12\x04chat\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12%\n" +
	"\x04type\x18\x05 \x01(\x0e2\x11.chat.MessageTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"a\n" +
	"\x15MessageHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x122\n" +
	"\x06before\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\"\x86\x01\n" +
	"\x13BulkMessageResponse\x12\x1d\n" +
	"\n" +
	"total_sent\x18\x01 \x01(\x05R\ttotalSent\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x05R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*#\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x012\xd0\x01\n" +
	"\vChatService\x126\n" +
	"\n" +
	"StreamChat\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x010\x01\x12E\n" +
	"\x11GetMessageHistory\x12\x1b.chat.MessageHistoryRequest\x1a\x11.chat.ChatMessage0\x01\x12B\n" +
	"\x10SendBulkMessages\x12\x11.chat.ChatMessage\x1a\x19.chat.BulkMessageResponse(\x01B\x1aZ\x18realtime-chat/proto/chatb\x06proto3"

var (
	file_kakaoTalk_proto_rawDescOnce sync.Once
	file_kakaoTalk_proto_rawDescData []byte
)

func file_kakaoTalk_proto_rawDescGZIP() []byte {
	file_kakaoTalk_proto_rawDescOnce.Do(func() {
		file_kakaoTalk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kakaoTalk_proto_rawDesc), len(file_kakaoTalk_proto_rawDesc)))
	})
	return file_kakaoTalk_proto_rawDescData
}

var file_kakaoTalk_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kakaoTalk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kakaoTalk_proto_goTypes = []any{
	(MessageType)(0),              // 0: chat.MessageType
	(*ChatMessage)(nil),           // 1: chat.ChatMessage
	(*MessageHistoryRequest)(nil), // 2: chat.MessageHistoryRequest
	(*BulkMessageResponse)(nil),   // 3: chat.BulkMessageResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_kakaoTalk_proto_depIdxs = []int32{
	0, // 0: chat.ChatMessage.type:type_name -> chat.MessageType
	4, // 1: chat.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: chat.MessageHistoryRequest.before:type_name -> google.protobuf.Timestamp
	1, // 3: chat.ChatService.StreamChat:input_type -> chat.ChatMessage
	2, // 4: chat.ChatService.GetMessageHistory:input_type -> chat.MessageHistoryRequest
	1, // 5: chat.ChatService.SendBulkMessages:input_type -> chat.ChatMessage
	1, // 6: chat.ChatService.StreamChat:output_type -> chat.ChatMessage
	1, // 7: chat.ChatService.GetMessageHistory:output_type -> chat.ChatMessage
	3, // 8: chat.ChatService.SendBulkMessages:output_type -> chat.BulkMessageResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kakaoTalk_proto_init() }
func file_kakaoTalk_proto_init() {
	if File_kakaoTalk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kakaoTalk_proto_rawDesc), len(file_kakaoTalk_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kakaoTalk_proto_goTypes,
		DependencyIndexes: file_kakaoTalk_proto_depIdxs,
		EnumInfos:         file_kakaoTalk_proto_enumTypes,
		MessageInfos:      file_kakaoTalk_proto_msgTypes,
	}.Build()
	File_kakaoTalk_proto = out.File
	file_kakaoTalk_proto_goTypes = nil
	file_kakaoTalk_proto_depIdxs = nil
}
